# Generated by Django 5.0.3 on 2024-03-26 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
